"""Recap files live under the Frigate media directory.

``/media/frigate/recap/<camera>/<id>/manifest.json`` plus ``video.mp4``
and ``thumb.jpg``. The manifest is the list the UI reads, so it is
rewritten in place as a job moves from queued to complete.
"""

from __future__ import annotations

import json
import logging
import os
import shutil
import time
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

from frigate.const import RECAP_DIR

logger = logging.getLogger(__name__)

# A Last 1 hour button and a custom range a few seconds off still match.
_HOUR_SLACK_SECONDS = 90

MANIFEST = "manifest.json"
VIDEO = "video.mp4"
THUMB = "thumb.jpg"


def recap_root() -> Path:
    return Path(RECAP_DIR)


def camera_dir(camera: str) -> Path:
    return recap_root() / camera


def recap_dir(camera: str, recap_id: str) -> Path:
    return camera_dir(camera) / recap_id


def safe_id(value: str) -> bool:
    """Ids are generated by Frigate and never contain a path separator."""
    if not value or len(value) > 160:
        return False
    return all(ch.isalnum() or ch in "._-" for ch in value)


def ensure_tree(camera: str, recap_id: str) -> Path:
    path = recap_dir(camera, recap_id)
    path.mkdir(parents=True, exist_ok=True)
    return path


ROLLING_SUFFIX = "_rolling"
ROLLING_REASON = "rolling"


def rolling_id(camera: str) -> str:
    """Fixed id of a camera's rolling recap. It is rebuilt in place."""
    return f"{camera}{ROLLING_SUFFIX}"


def is_rolling(manifest: dict[str, Any]) -> bool:
    return str(manifest.get("reason") or "") == ROLLING_REASON or str(
        manifest.get("id") or ""
    ).endswith(ROLLING_SUFFIX)


def staging_dir(recap_id: str) -> Path:
    """Build directory for a rolling refresh. A leading dot keeps it out of lists."""
    return recap_root() / ".staging" / recap_id


def swap_into_place(staging: Path, camera: str, recap_id: str) -> Path:
    """Replace the live rolling recap with a finished build.

    The old folder is renamed aside before the new one is renamed in, so
    a reader sees either the old recap or the new one. A video already
    being streamed keeps playing from the old file until it is closed.
    """
    target = recap_dir(camera, recap_id)
    target.parent.mkdir(parents=True, exist_ok=True)
    retired = staging.parent / f"{recap_id}.old"
    if retired.exists():
        shutil.rmtree(retired, ignore_errors=True)
    if target.exists():
        os.replace(target, retired)
    os.replace(staging, target)
    shutil.rmtree(retired, ignore_errors=True)
    return target


def write_manifest(directory: Path, payload: dict[str, Any]) -> None:
    """Atomic replace so a reader never sees a half-written manifest."""
    target = directory / MANIFEST
    temporary = directory / f"{MANIFEST}.tmp"
    temporary.write_text(json.dumps(payload))
    os.replace(temporary, target)


def read_manifest(directory: Path) -> dict[str, Any] | None:
    path = directory / MANIFEST
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(data, dict):
        return None
    return data


def update_manifest(directory: Path, **fields: Any) -> dict[str, Any]:
    current = read_manifest(directory) or {}
    current.update(fields)
    current["updated"] = time.time()
    write_manifest(directory, current)
    return current


def _scan(root: Path) -> list[dict[str, Any]]:
    """Summaries stored under one recap root. The root itself is not a camera."""
    found: list[dict[str, Any]] = []
    if not root.is_dir():
        return found
    for camera_path in root.iterdir():
        if not camera_path.is_dir() or camera_path.name.startswith("."):
            continue
        for recap_path in camera_path.iterdir():
            if not recap_path.is_dir():
                continue
            manifest = read_manifest(recap_path)
            if manifest is None:
                continue
            found.append(_summary(manifest))
    return found


def recap_order_key(item: dict[str, Any]) -> tuple[float, float]:
    """Newest window end first, then the newest creation time.

    The end of the footage matters more than when the file was written,
    and the order is the same for every camera and kind.
    """
    return (
        float(item.get("before") or 0),
        float(item.get("created") or 0),
    )


def list_recaps() -> list[dict[str, Any]]:
    """Local recaps, newest window first. Retention uses this list and ignores the archive."""
    found = _scan(recap_root())
    found.sort(key=recap_order_key, reverse=True)
    return found


def list_visible_recaps(archive_dirs: list[Path]) -> list[dict[str, Any]]:
    """Local recaps plus older copies on mounted archives.

    A recap that still exists locally is listed once, as the local copy.
    """
    local = list_recaps()
    for item in local:
        item["source"] = "local"
    seen = {str(item.get("id") or "") for item in local}
    merged = list(local)
    for directory in archive_dirs:
        for item in _scan(directory):
            recap_id = str(item.get("id") or "")
            if not recap_id or recap_id in seen:
                continue
            item["source"] = "archive"
            if not item.get("status"):
                item["status"] = "complete"
            seen.add(recap_id)
            merged.append(item)
    merged.sort(key=recap_order_key, reverse=True)
    return merged


def summary_categories(value: Any) -> list[dict[str, Any]]:
    """Per-type counts for the recap cards. Track geometry stays on the detail call."""
    if not isinstance(value, list):
        return []
    counts: list[dict[str, Any]] = []
    for item in value:
        if not isinstance(item, dict):
            continue
        try:
            count = int(item.get("count") or 0)
        except (TypeError, ValueError):
            count = 0
        counts.append(
            {
                "key": str(item.get("key") or ""),
                "name": str(item.get("name") or ""),
                "color": str(item.get("color") or ""),
                "count": count,
            }
        )
    return counts


def _summary(manifest: dict[str, Any]) -> dict[str, Any]:
    """Fields the list view needs. The full track list stays on the detail call."""
    return {
        "id": manifest.get("id"),
        "camera": manifest.get("camera"),
        "status": manifest.get("status"),
        "progress": manifest.get("progress", 0),
        "message": manifest.get("message", ""),
        "created": manifest.get("created"),
        "after": manifest.get("after"),
        "before": manifest.get("before"),
        "seconds": manifest.get("seconds"),
        "event_count": manifest.get("event_count", 0),
        "width": manifest.get("width"),
        "height": manifest.get("height"),
        "reason": manifest.get("reason") or "",
        "kind": manifest.get("kind") or "",
        "explicit_range": bool(manifest.get("explicit_range")),
        "source": manifest.get("source") or "",
        "categories": summary_categories(manifest.get("categories")),
        "started": manifest.get("started"),
        "finished": manifest.get("finished"),
        "took_s": manifest.get("took_s"),
        "checked": manifest.get("checked"),
        "stage": manifest.get("stage") or "",
        "hours": manifest.get("hours"),
    }


def delete_recap(camera: str, recap_id: str) -> bool:
    path = recap_dir(camera, recap_id)
    if not path.is_dir():
        return False
    shutil.rmtree(path, ignore_errors=True)
    return True


def find_manifest(
    recap_id: str, extra_dirs: list[Path] | None = None
) -> tuple[Path, dict[str, Any]] | None:
    """Locate a recap by id without trusting a camera name from the client.

    ``extra_dirs`` are archive ``recap/`` directories. Local media is searched
    first so a recap that has not been deleted yet stays the one that plays.
    """
    if not safe_id(recap_id):
        return None
    roots = [recap_root()]
    if extra_dirs:
        roots.extend(extra_dirs)
    for root in roots:
        if not root.is_dir():
            continue
        for camera_path in root.iterdir():
            if not camera_path.is_dir() or camera_path.name.startswith("."):
                continue
            directory = camera_path / recap_id
            manifest = read_manifest(directory)
            if manifest is not None and manifest.get("id") == recap_id:
                return directory, manifest
    return None


def purge_expired(retain_days_for: dict[str, int], now: float | None = None) -> int:
    """Delete recaps older than the camera's retain_days. 0 keeps them."""
    moment = time.time() if now is None else now
    removed = 0
    for summary in list_recaps():
        camera = str(summary.get("camera") or "")
        days = retain_days_for.get(camera)
        if not days:
            continue
        created = float(summary.get("created") or moment)
        if moment - created < days * 86400:
            continue
        if summary.get("status") in ("queued", "running"):
            continue
        if is_rolling(summary):
            continue
        recap_id = str(summary.get("id") or "")
        if safe_id(camera) and safe_id(recap_id) and delete_recap(camera, recap_id):
            removed += 1
    return removed


def _epoch_token(value: float) -> str:
    """Stable text for a range kind so the same window always matches."""
    number = float(value)
    if number.is_integer():
        return str(int(number))
    return format(number, "f").rstrip("0").rstrip(".")


def _at_local_midnight(moment: datetime) -> bool:
    return (
        moment.hour == 0
        and moment.minute == 0
        and moment.second == 0
        and moment.microsecond == 0
    )


def calendar_day(after: float, before: float, zone) -> str | None:
    """Local date when the window is exactly one midnight-to-midnight day.

    The date is the day that starts at ``after``. A 23-hour or 25-hour
    civil day still counts, because daylight saving changes the length
    and not the midnights. Any other window is not a calendar day.
    """
    start = datetime.fromtimestamp(float(after), tz=zone)
    end = datetime.fromtimestamp(float(before), tz=zone)
    if not _at_local_midnight(start) or not _at_local_midnight(end):
        return None
    if end.date() != start.date() + timedelta(days=1):
        return None
    return start.date().isoformat()


def recap_kind(
    reason: str,
    after: float,
    before: float,
    zone,
    *,
    explicit: bool = False,
) -> str:
    """Group key for duplicate recaps of one camera.

    Last-N-hours buttons group by window length (``last-6h``, ``last-90m``).
    An explicit after/before range never uses that grouping. One local
    midnight-to-midnight day is ``day:<date>``, the same kind as the
    nightly recap for that date. Any other explicit range is
    ``range:<after>-<before>``. Nightly jobs group by the calendar day
    of the window end in the UI timezone.
    """
    if explicit:
        day = calendar_day(after, before, zone)
        if day:
            return f"day:{day}"
        return f"range:{_epoch_token(after)}-{_epoch_token(before)}"
    if reason in {"schedule", "backfill"}:
        end = datetime.fromtimestamp(float(before), tz=zone)
        return f"day:{end.date().isoformat()}"
    span = max(0.0, float(before) - float(after))
    if reason == "interval":
        # Separate from last-Nh and from the in-place rolling recap, so
        # only another run of this same interval replaces it.
        minutes = max(1, int(round(span / 60)))
        return f"rolling-{minutes}m"
    nearest_hour = int(round(span / 3600))
    if nearest_hour >= 1 and abs(span - nearest_hour * 3600) <= _HOUR_SLACK_SECONDS:
        return f"last-{nearest_hour}h"
    minutes = max(1, int(round(span / 60)))
    return f"last-{minutes}m"


def group_kind(kind: str) -> str:
    """Kind used when deciding which completed recap replaces another.

    Live backfills were labeled ``backfill-day:<date>``. That is the
    same group as ``day:<date>``.
    """
    prefix = "backfill-day:"
    if kind.startswith(prefix):
        return f"day:{kind[len(prefix) :]}"
    return kind


def kind_of(manifest: dict[str, Any], zone) -> str:
    """Stored kind, or the kind implied by reason and the window."""
    stored = str(manifest.get("kind") or "")
    if stored:
        return group_kind(stored)
    return group_kind(
        recap_kind(
            str(manifest.get("reason") or ""),
            float(manifest.get("after") or 0),
            float(manifest.get("before") or 0),
            zone,
            explicit=bool(manifest.get("explicit_range")),
        )
    )


def remove_superseded(
    camera: str,
    recap_id: str,
    zone,
    *,
    enabled: bool = True,
) -> list[str]:
    """Delete older completed local recaps of the same camera and kind.

    No-op unless the new recap is already complete and Ready. Running,
    failed, queued, cancelled, and archive-sourced recaps are kept, and
    the recap that just finished is never deleted.
    """
    if not enabled:
        return []
    found = find_manifest(recap_id)
    if found is None:
        return []
    directory, manifest = found
    try:
        directory.resolve().relative_to(recap_root().resolve())
    except ValueError:
        return []
    if manifest.get("status") != "complete" or manifest.get("message") != "Ready":
        return []
    if str(manifest.get("source") or "") == "archive":
        return []
    kind = kind_of(manifest, zone)
    created = float(manifest.get("created") or 0)
    camera_name = str(manifest.get("camera") or camera)
    if not safe_id(camera_name):
        return []
    removed: list[str] = []
    for summary in list_recaps():
        other_id = str(summary.get("id") or "")
        if not other_id or other_id == recap_id:
            continue
        if str(summary.get("camera") or "") != camera_name:
            continue
        if summary.get("status") != "complete":
            continue
        if str(summary.get("source") or "") == "archive":
            continue
        if float(summary.get("created") or 0) > created:
            continue
        if kind_of(summary, zone) != kind:
            continue
        if not safe_id(other_id):
            continue
        if not delete_recap(camera_name, other_id):
            continue
        logger.info(
            "Removed superseded recap %s for %s (%s)",
            other_id,
            camera_name,
            kind,
        )
        removed.append(other_id)
    return removed
