"""Recap files live under the Frigate media directory.

``/media/frigate/recap/<camera>/<id>/manifest.json`` plus ``video.mp4``
and ``thumb.jpg``. The manifest is the list the UI reads, so it is
rewritten in place as a job moves from queued to complete.
"""

from __future__ import annotations

import json
import os
import shutil
import time
from pathlib import Path
from typing import Any

from frigate.const import RECAP_DIR

MANIFEST = "manifest.json"
VIDEO = "video.mp4"
THUMB = "thumb.jpg"


def recap_root() -> Path:
    return Path(RECAP_DIR)


def camera_dir(camera: str) -> Path:
    return recap_root() / camera


def recap_dir(camera: str, recap_id: str) -> Path:
    return camera_dir(camera) / recap_id


def safe_id(value: str) -> bool:
    """Ids are generated by Frigate and never contain a path separator."""
    if not value or len(value) > 160:
        return False
    return all(ch.isalnum() or ch in "._-" for ch in value)


def ensure_tree(camera: str, recap_id: str) -> Path:
    path = recap_dir(camera, recap_id)
    path.mkdir(parents=True, exist_ok=True)
    return path


def write_manifest(directory: Path, payload: dict[str, Any]) -> None:
    """Atomic replace so a reader never sees a half-written manifest."""
    target = directory / MANIFEST
    temporary = directory / f"{MANIFEST}.tmp"
    temporary.write_text(json.dumps(payload))
    os.replace(temporary, target)


def read_manifest(directory: Path) -> dict[str, Any] | None:
    path = directory / MANIFEST
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(data, dict):
        return None
    return data


def update_manifest(directory: Path, **fields: Any) -> dict[str, Any]:
    current = read_manifest(directory) or {}
    current.update(fields)
    current["updated"] = time.time()
    write_manifest(directory, current)
    return current


def _scan(root: Path) -> list[dict[str, Any]]:
    """Summaries stored under one recap root. The root itself is not a camera."""
    found: list[dict[str, Any]] = []
    if not root.is_dir():
        return found
    for camera_path in root.iterdir():
        if not camera_path.is_dir() or camera_path.name.startswith("."):
            continue
        for recap_path in camera_path.iterdir():
            if not recap_path.is_dir():
                continue
            manifest = read_manifest(recap_path)
            if manifest is None:
                continue
            found.append(_summary(manifest))
    return found


def list_recaps() -> list[dict[str, Any]]:
    """Local recaps, newest first. Retention uses this list and ignores the archive."""
    found = _scan(recap_root())
    found.sort(key=lambda item: float(item.get("created") or 0), reverse=True)
    return found


def list_visible_recaps(archive_dirs: list[Path]) -> list[dict[str, Any]]:
    """Local recaps plus older copies on mounted archives.

    A recap that still exists locally is listed once, as the local copy.
    """
    local = list_recaps()
    for item in local:
        item["source"] = "local"
    seen = {str(item.get("id") or "") for item in local}
    merged = list(local)
    for directory in archive_dirs:
        for item in _scan(directory):
            recap_id = str(item.get("id") or "")
            if not recap_id or recap_id in seen:
                continue
            item["source"] = "archive"
            if not item.get("status"):
                item["status"] = "complete"
            seen.add(recap_id)
            merged.append(item)
    merged.sort(key=lambda item: float(item.get("created") or 0), reverse=True)
    return merged


def _summary(manifest: dict[str, Any]) -> dict[str, Any]:
    """Fields the list view needs. The full track list stays on the detail call."""
    return {
        "id": manifest.get("id"),
        "camera": manifest.get("camera"),
        "status": manifest.get("status"),
        "progress": manifest.get("progress", 0),
        "message": manifest.get("message", ""),
        "created": manifest.get("created"),
        "after": manifest.get("after"),
        "before": manifest.get("before"),
        "seconds": manifest.get("seconds"),
        "event_count": manifest.get("event_count", 0),
        "width": manifest.get("width"),
        "height": manifest.get("height"),
    }


def delete_recap(camera: str, recap_id: str) -> bool:
    path = recap_dir(camera, recap_id)
    if not path.is_dir():
        return False
    shutil.rmtree(path, ignore_errors=True)
    return True


def find_manifest(
    recap_id: str, extra_dirs: list[Path] | None = None
) -> tuple[Path, dict[str, Any]] | None:
    """Locate a recap by id without trusting a camera name from the client.

    ``extra_dirs`` are archive ``recap/`` directories. Local media is searched
    first so a recap that has not been deleted yet stays the one that plays.
    """
    if not safe_id(recap_id):
        return None
    roots = [recap_root()]
    if extra_dirs:
        roots.extend(extra_dirs)
    for root in roots:
        if not root.is_dir():
            continue
        for camera_path in root.iterdir():
            if not camera_path.is_dir() or camera_path.name.startswith("."):
                continue
            directory = camera_path / recap_id
            manifest = read_manifest(directory)
            if manifest is not None and manifest.get("id") == recap_id:
                return directory, manifest
    return None


def purge_expired(retain_days_for: dict[str, int], now: float | None = None) -> int:
    """Delete recaps older than the camera's retain_days. 0 keeps them."""
    moment = time.time() if now is None else now
    removed = 0
    for summary in list_recaps():
        camera = str(summary.get("camera") or "")
        days = retain_days_for.get(camera)
        if not days:
            continue
        created = float(summary.get("created") or moment)
        if moment - created < days * 86400:
            continue
        if summary.get("status") in ("queued", "running"):
            continue
        recap_id = str(summary.get("id") or "")
        if safe_id(camera) and safe_id(recap_id) and delete_recap(camera, recap_id):
            removed += 1
    return removed
